title: Darshankumar Bapodariya # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M.Sc Computer Science with a strong background in Data Science. 
  
  <br><br>
  Tools: Python, SQL, PowerBI, Azure Databricks, Excel 
  <br><br>
  <a href="https://www.linkedin.com/in/darshan-bapodariya/">LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/DarshanBapodariya?tab=repositories">GitHub Repo</a>
  <br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
